<?php
/**
 * ItemsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shopping List Backend Service
 *
 * This service provides endpoints for all related interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ikmarv@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ItemsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createShoppingList
     *
     * Create a new todo shopping list item.
     *
     */
    public function testCreateShoppingList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retrieveSingleShoppingList
     *
     * Retrieve a single todo shopping list item by ID.
     *
     */
    public function testRetrieveSingleShoppingList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retriveTodoList
     *
     * Retrieve a list of all todo shopping list items.
     *
     */
    public function testRetriveTodoList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateTodoShoppingList
     *
     * Update a todo shopping list item.
     *
     */
    public function testUpdateTodoShoppingList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
